BACKGROUND_COLOR = "dark"
DEFAULT_COLOR_THEME = "green"
LOGIN_SUCCESS_COLOR = "green"
LOGIN_FAILED_COLOR = "red"


DEFAULT_FONT = ("Fixedsys", 24)
LOGIN_TITLE_FONT = ("Fixedsys", 36, "bold")

WINDOW_SIZE = "1000x700"
LABEL_PADY = 20
ENTRY_PADY = 15
BUTTON_PADY = 30
LOGIN_SUCCESS_PADY = 20
CREATE_ACCOUNT_BUTTON_PADY = 30
